### ISSUE TITLE
[Feature Request] Show additional trade info

### ISSUE THREAD

**Issue by Bluscream** [Ryzhehvost/ItemDispenser#3]
I would appreciate if the plugin would display additional info about the trade in the log, such as:
- Name of the items
- Name (steamid64) of the trader
- Trade message if given by the trader

**Comment by Ryzhehvost** [comment]
It will make asf behavior inconsistent, since you will get this info only for trades handled by plugin, but not for trades handled by ASF itself. Unsure if I want to implement it this way.

**Comment by Bluscream** [comment]
Why not leave it as an additional setting that can be toggled manually. That way people wanting a consistent behavior won't be bothered by it

**Comment by Ryzhehvost** [comment]
I guess I will decline this feature request after all. Additional logging for trades should be done within ASF itself, or as a separate plugin (but the latter will require changes on ASF side anyway, since for now ASF does not return all required data for accepted trades).

**Comment by Bluscream** [comment]
Gotcha, thanks anyway. If logging will be done through another plugin, is there any way for that plugin to check wether it was your plugin that accepted the trade?

**Comment by Ryzhehvost** [comment]
I don't think so
