### ISSUE TITLE
привет мир-privet mir-Hello World 

### ISSUE THREAD

**Issue by wollframium** [Ryzhehvost/ItemDispenser#7]
hi, tell me, is there any kind of restriction per person? Let's say 1 person will send me 1000 offers for 1 subject. or on all items at once, and the distribution will not come out all will be taken by 1 person.

**Comment by Ryzhehvost** [comment]
For now there are no restrictions. This was already suggested in #4, But I don't have time to implement it. Feel free to send PR if you want.
